# theme: jekyll-theme-leap-day
# Site
name: "Noah Boot - Fundraising Page"
title: "Noah Boot - Fundraising Page"
description: "A fundraising page for Birkenshaw C.E. (C) Primary School to raise money for the annual costs of their school bus."
remote_theme: wowthemesnet/mediumish-theme-jekyll

background_colour: "linear-gradient(180deg, #7de074, #ffffff)"
goalcurrent: "£21.50"
goalcurrentpercentage: "106%"
goaltarget: "£20.22"

include: ["_pages"]
