# theme: jekyll-theme-leap-day
# Site
name: "Joseph Boot - Fundraising Page"
title: "Joseph Boot - Fundraising Page"
description: "A fundraising page for Birkenshaw C.E. (C) Primary School to raise money for the annual costs of their school bus."
remote_theme: wowthemesnet/mediumish-theme-jekyll

background_colour: "#95f3ff"
goalcurrent: "£0.00"
goalcurrentpercentage: "0%"
goaltarget: "£20.22"

include: ["_pages"]